ci: CI/CD {
    jenkins: Jenkins Master
    job: Scan Job
    sbomnix
    signer: Custom Signer
    nix_daemon: Nix Daemon

    jenkins <-> job: Trigger Scan

    job -> sbomnix: Paths to scan
    sbomnix -> nix_daemon: vulnerability scans
    sbomnix -> signer: scan artefacts
    signer -> job: signed artefacts
    signer -> upload: signed artefacts {
        style.stroke-dash: 3
    }
}

ci.upload -> cache

cache: Binary Cache

artefact_store: Artefact Store ??? {
     style.stroke-dash: 3
}


cache -> ci.nix_daemon: substitute paths {
    style {
        stroke-dash: 3
    }
}

ci.job -> artefact_store {
    style.stroke-dash: 3
}
